name: Generate Snake Animation

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false   # Token'ın push için kullanılabilmesi için

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Arda-Yalcin
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit snake files
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generated snake animation"
          add: "dist/*.svg"
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Kendi PAT token'ını buraya ekle
